{
 "title": "ICMP Monitor",
 "description": "Graph ICMP metrics from the blackbox exporter, Smokeping-style",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ICMP RTT",
   "type": "stat",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP packet loss",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "1-avg_over_time(probe_success{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time ($instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "repeat": "instance",
   "yaxes": [
    { "format": "dtdurations", "label": "RTT" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\",instance=~\"$instance\"}) by (instance) > 0",
     "legendFormat": "RTT"
    },
    {
     "expr": "1-avg_over_time(probe_success{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "packet loss"
    }
   ]
  }
 ]
}