# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: NODE-EXPORTER
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 172.18.0.5:9100
      labels:
        environment: dev
        cluster: node-exporter-clus
        role: Demo
        applicationId: NODE-EXPORTER
        hname: node-exporter-node1
        type: linux

  - job_name: COLLECTD-EXPORTER
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 172.18.0.7:9103
      labels:
        environment: dev
        cluster: collectd-exporter-clus
        role: Demo
        applicationId: COLLECTD-EXPORTER
        hname: collectd-exporter-node1
        type: linux

  - job_name: BLACKBOX-EXPORTER-HTTP
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: 
       - http_2xx
       - icmp  # Look for a HTTP 200 response.
    scheme: http 
    static_configs:
      - targets:
        - http://172.18.0.2:9090
        - http://172.18.0.4:3000
        - https://www.github.com
        - https://www.grafana.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 172.18.0.6:9115
  
  - job_name: BLACKBOX-EXPORTER-ICMP
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
        - 172.18.0.2
        - 172.18.0.3
        - 172.18.0.4
        - 172.18.0.5
        - 172.18.0.6
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.6:9115  # This is your blackbox exporter.

    
